name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # install dependencies
    - name: install boost
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev

    - name: install nlohmann-json
      run: sudo apt install -yq nlohmann-json3-dev

    # build project
    - name: mkdir
      run: mkdir build

    - name: cmake build
      run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=build/install

    - name: cmake make
      run: cmake --build build/

    - name: cmake install
      run: sudo cmake --install build/

    # set up and run the single actor tests
    - name: "tests: install gtest"
      run: sudo apt install -yq libgtest-dev

    - name: "tests: mkdir"
      working-directory: ./test
      run: mkdir build

    - name: "tests: cmake"
      working-directory: ./test
      run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=../build/install

    - name: "tests: build"
      working-directory: ./test/build
      run: cmake --build .

    - name: "tests: install"
      working-directory: ./test/build
      run: cmake --install .

    - name: "tests: run semantics tests"
      working-directory: ./test/build
      run: source ../setup.bash && ./test_semantics

    - name: "tests: run external changes tests"
      working-directory: ./test/build
      run: source ../setup.bash && ./test_external_changes

    #
    # set up and run the multi actor tests
    #

    - name: "tests::cyclonedds: mkdir"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds
      run: mkdir build

    - name: "tests::cyclonedds: cmake"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds
      run: cmake -Bbuild -H.

    - name: "tests::cyclonedds: build"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds
      run: cmake --build ./build

    - name: "tests::cyclonedds: install"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds
      run: sudo cmake --install ./build


    - name: "tests::cyclonedds-cxx: mkdir"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds-cxx
      run: mkdir build

    - name: "tests::cyclonedds-cxx: cmake"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds-cxx
      run: cmake -Bbuild -H.

    - name: "tests::cyclonedds-cxx: build"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds-cxx
      run: cmake --build ./build

    - name: "tests::cyclonedds-cxx: install"
      working-directory: ./test/action_sync_cyclone_dds/cyclonedds-cxx
      run: sudo cmake --install ./build


    - name: "tests::sync-plugin: mkdir"
      working-directory: ./test/action_sync_cyclone_dds
      run: mkdir build

    - name: "tests::sync-plugin: cmake"
      working-directory: ./test/action_sync_cyclone_dds
      run: cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=./../../build/install

    - name: "tests::sync-plugin: build"
      working-directory: ./test/action_sync_cyclone_dds
      run: cmake --build ./build

    - name: "tests::sync-plugin: install"
      working-directory: ./test/action_sync_cyclone_dds
      run: sudo cmake --install ./build


    - name: "tests: run multi actor test"
      working-directory: ./test
      run: source setup.bash && bash src/multi_actor_sync_test.bash
